# Generated by Django 4.2.4 on 2023-09-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_email_contact_emails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='names',
            new_name='name',
        ),
    ]
