# Generated by Django 3.0.5 on 2023-10-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20231003_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickenquiry',
            name='service',
            field=models.CharField(choices=[('1', 'High'), ('2', 'Medium'), ('3', 'Low')], default='1', max_length=1),
        ),
    ]
