# Generated by Django 3.0.5 on 2023-10-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20231003_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('dogname', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('petexperience', models.CharField(max_length=255)),
                ('previouspets', models.CharField(max_length=255)),
                ('declaration', models.CharField(max_length=255)),
            ],
        ),
    ]
