# Generated by Django 4.2.5 on 2023-10-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_donation_delete_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogAdopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('dogname', models.CharField(choices=[('Sheru', 'Sheru'), ('Moti', 'Moti'), ('Tiger', 'Tiger'), ('Lucy', 'Lucy'), ('Danny', 'Danny'), ('Marco', 'Marco')], max_length=255)),
                ('reason', models.TextField()),
                ('petexperience', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('previouspets', models.TextField(blank=True, null=True)),
                ('declaration', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Adoptform',
        ),
    ]
