# Generated by Django 4.2.5 on 2023-10-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_dogadopt_delete_adoptform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadopt',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='dogadopt',
            name='petexperience',
        ),
    ]
