# Generated by Django 4.2.5 on 2023-10-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_dogadopt_declaration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogadopt',
            name='previouspets',
        ),
        migrations.RemoveField(
            model_name='dogadopt',
            name='reason',
        ),
    ]
