# Generated by Django 4.2.5 on 2023-10-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_dogadopt_previouspets_remove_dogadopt_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadopt',
            name='dogname',
            field=models.CharField(choices=[('Sheru', 'Sheru'), ('Moti', 'Moti'), ('Tiger', 'Tiger'), ('Lucy', 'Lucy'), ('Danny', 'Danny'), ('Marco', 'Marco')], max_length=5),
        ),
    ]
