# Generated by Django 4.2.5 on 2023-10-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_dogadopt_dogname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadopt',
            name='dogname',
            field=models.CharField(choices=[('Sheru', 'Sheru'), ('Moti', 'Moti'), ('Tiger', 'Tiger'), ('Lucy', 'Lucy'), ('Danny', 'Danny'), ('Marco', 'Marco')], default='1', max_length=10),
        ),
    ]
